#ifdef VENDOR_EDIT
obj-$(CONFIG_OPPO_DEVICE_IFNO)  +=  oppo_devinfo/

obj-y += oppo_custom/

obj-y  +=  oppo_criticallog/

#ifdef OPLUS_FEATURE_NFC_CONSOFT
obj-$(CONFIG_OPPO_NFC)     +=  oppo_nfc/
#endif /* OPLUS_FEATURE_NFC_CONSOFT */

#ifdef OPLUS_FEATURE_SENSOR_SMEM
obj-$(CONFIG_OPPO_ALS_CALI)   +=  oppo_als_cali_value/
#endif /*OPLUS_FEATURE_SENSOR_SMEM */

#ifdef OPLUS_FEATURE_MEMLEAK_DETECT
obj-$(CONFIG_OPPO_SVELTE)     +=  oppo_svelte/
#endifi /* OPLUS_FEATURE_MEMLEAK_DETECT */

#ifdef VENDOR_EDIT
obj-$(CONFIG_OPPO_WAKELOCK_PROFILER)     +=  oppo_wakelock_profiler/
#endif /* VENDOR_EDIT */

#ifdef OPLUS_FEATURE_MEMLEAK_DETECT
obj-$(CONFIG_OPPO_SVELTE)     +=  oppo_svelte/
#endifi /* OPLUS_FEATURE_MEMLEAK_DETECT */
